// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/7/2025, 11:33:23 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/hongmengzhai/Documents/Coding/nidonestfest/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/plugins/**/*.{js,ts,mjs}","/Users/hongmengzhai/Documents/Coding/nidonestfest/composables/**/*.{js,ts,mjs}","/Users/hongmengzhai/Documents/Coding/nidonestfest/utils/**/*.{js,ts,mjs}","/Users/hongmengzhai/Documents/Coding/nidonestfest/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hongmengzhai/Documents/Coding/nidonestfest/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;